# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        args: [ '-m', 'HANGING_INDENT', '-l', '120','--check-only' ]
        files: .

  - repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
        args: [ '--max-line-length=127' ]
        files: \.py$